name: Push CI Docker image
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  push:
    branches:
      - 'main'
      - 'v*'
  workflow_dispatch:

jobs:
  push-ci-docker-image:
    name: Start push-ci-docker-image
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    runs-on:
      - self-hosted
      - small
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: make docker push
        run: make ci.docker.run RUN_WHAT="make ci.docker.push"
