name: Push CI Docker image
on:
  workflow_run:
    workflows: [pre-commit]
    types:
      - completed

env:
  DOCKER_USERNAME: "${{ secrets.DOCKER_READ_WRITE_USERNAME }}"
  DOCKER_PASSWORD: "${{ secrets.DOCKER_READ_WRITE_PASSWORD }}"

jobs:
  push-ci-docker-image:
    name: Start push-ci-docker-image
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ok-to-test'))  }}
    runs-on:
      - self-hosted
      - small
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: make docker push
        run: make ci.docker.run RUN_WHAT="make ci.docker.push"
